### ISSUE TITLE
to many send api key operations - SendSSHPublicKey 

### ISSUE THREAD

**Issue by zschorn** [mpieters3/ansible-eci-connector#3]
First of all, really a great plugin, exactly what we searched for a long time.

Plugin in general works, but we get randomly errors, i assume the task are too fast.
Log shows that for each task, a new SendSSHPublicKey  is executed. 

What can we do to throttle down the api-calls? Log shows that you had already had an idea.
```
ECI PUB KEY EXPIRING/NOT SENT, PUSHING NOW
```
[extensiveLog.txt](https://github.com/mpieters3/ansible-eci-connector/files/5003496/extensiveLog.txt)

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.errorfactory.ThrottlingException: An error occurred (ThrottlingException) when calling the SendSSHPublicKey operation (reached max retries: 4): Server is busy! Please retry after a moment.
fatal: [10.4.8.11]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

```

**Comment by mpieters3** [comment]
I'll take a look

**Comment by mpieters3** [comment]
@zschorn @budgester  - very much overdue, but try the version of the module located on this branch:
https://github.com/mpieters3/ansible-eci-connector/tree/feature/connection_caching 

Don't have enough load to test it in my local dev, but it should be better about caching
